const FACE_MODEL_URL="https://justadudewhohacks.github.io/face-api.js/models",DB="northstar-vision",STORE="people",FACE_LIMIT=.52,VOICE_LIMIT=.78,MAX_PHOTOS=6,VOICE_MS=6000;
const $=s=>document.querySelector(s),el={camera:$("#camera"),photo:$("#photoPreview"),overlay:$("#overlay"),stage:$("#stage"),modelStatus:$("#modelStatus"),sourceTitle:$("#sourceTitle"),scanHint:$("#scanHint"),fileStatus:$("#fileStatus"),cameraButton:$("#cameraButton"),imageInput:$("#imageInput"),captureButton:$("#captureButton"),stopButton:$("#stopButton"),fullscreenButton:$("#fullscreenButton"),resultList:$("#resultList"),recognitionSummary:$("#recognitionSummary"),clearLogButton:$("#clearLogButton"),peopleCount:$("#peopleCount"),personGrid:$("#personGrid"),personTemplate:$("#personTemplate"),enrollButton:$("#enrollButton"),emptyEnrollButton:$("#emptyEnrollButton"),enrollDialog:$("#enrollDialog"),enrollForm:$("#enrollForm"),personName:$("#personName"),enrollmentImages:$("#enrollmentImages"),dropZone:$("#dropZone"),fileCount:$("#fileCount"),enrollFeedback:$("#enrollFeedback"),savePersonButton:$("#savePersonButton"),closeEnrollButton:$("#closeEnrollButton"),privacyButton:$("#privacyButton"),privacyDialog:$("#privacyDialog"),closePrivacyButton:$("#closePrivacyButton"),speakerStrip:$("#speakerStrip"),speakerName:$("#speakerName"),speakerDetail:$("#speakerDetail"),listenButton:$("#listenButton"),voiceDialog:$("#voiceDialog"),closeVoiceButton:$("#closeVoiceButton"),cancelVoiceButton:$("#cancelVoiceButton"),voicePersonName:$("#voicePersonName"),recordVoiceButton:$("#recordVoiceButton"),recordMeter:$("#recordMeter"),recordSeconds:$("#recordSeconds"),voiceFeedback:$("#voiceFeedback")};
let objectModel,ready=false,active=null,kind="",cameraStream,photoURL,scanTimer,scanning=false,objects=[],nextObjects=0,lastResults=[],people=[];
let audioStream,audioContext,audioAnalyser,freq,time,listening=false,listenTimer,recording=false,recordTimer,voiceSamples=[],voiceId;

const setStatus=(text,isReady=false)=>{el.modelStatus.textContent=text;el.modelStatus.classList.toggle("ready",isReady);el.scanHint.textContent=text};
const escape=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const distance=(a,b)=>{let n=Math.min(a.length,b.length),t=0;if(!n)return Infinity;for(let i=0;i<n;i++)t+=(a[i]-b[i])**2;return Math.sqrt(t/n)};
const initials=name=>name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join("").toUpperCase()||"?";
const voices=()=>people.filter(p=>Array.isArray(p.voicePrint)&&p.voicePrint.length).length;
function db(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function getPeople(){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>{d.close();ok(r.result||[])};r.onerror=()=>{d.close();no(r.error)}})}
async function put(person){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).put(person);r.onsuccess=()=>{d.close();ok()};r.onerror=()=>{d.close();no(r.error)}})}
async function remove(id){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>{d.close();ok()};r.onerror=()=>{d.close();no(r.error)}})}
function speaker(name,detail,active=false){el.speakerName.textContent=name;el.speakerDetail.textContent=detail;el.speakerStrip.classList.toggle("listening",active)}
function renderPeople(){el.peopleCount.textContent=people.length;[...el.personGrid.querySelectorAll(".person-card")].forEach(x=>x.remove());for(let p of people){let c=el.personTemplate.content.firstElementChild.cloneNode(true),has=Array.isArray(p.voicePrint)&&p.voicePrint.length;c.querySelector(".initials").textContent=initials(p.name);c.querySelector("h3").textContent=p.name;c.querySelector(".face-status").textContent=`${p.descriptors.length} face sample${p.descriptors.length===1?"":"s"}`;c.querySelector(".voice-status").textContent=has?"Voice cue stored":"No voice cue";let teach=c.querySelector(".teach-voice-button");teach.textContent=has?"RETEACH VOICE":"TEACH VOICE";teach.onclick=()=>openVoice(p.id);c.querySelector(".forget-button").onclick=async()=>{if(!confirm(`Forget ${p.name}? Their face and voice profiles will be removed from this browser.`))return;await remove(p.id);people=people.filter(x=>x.id!==p.id);renderPeople();if(!voices())stopListening("No stored voice cues.")};el.personGrid.insertBefore(c,el.personGrid.firstChild)}el.listenButton.disabled=!voices();if(!voices()&&!listening)speaker("Microphone is off","Teach a voice cue, then start listening.")}
function faceMatch(d){let best={name:"Unknown face",distance:Infinity,known:false};for(let p of people)for(let stored of p.descriptors){let v=distance(d,stored)*Math.sqrt(d.length);if(v<best.distance)best={name:p.name,distance:v,known:v<=FACE_LIMIT}}return best.known?best:{name:"Unknown face",distance:best.distance,known:false}}
function renderResults(results){lastResults=results;let f=results.filter(x=>x.kind==="face").length,o=results.length-f;el.recognitionSummary.innerHTML=`<strong>${results.length||"—"}</strong><span>${results.length?`${f} FACE · ${o} OBJECT${o===1?"":"S"}`:"WAITING FOR A VIEW"}</span>`;if(!results.length){el.resultList.innerHTML='<div class="empty-results"><p>Faces and objects detected in the frame are listed here.</p></div>';return}el.resultList.innerHTML=results.slice(0,12).map(x=>{let conf=x.kind==="face"?(x.known?Math.round(Math.max(0,1-x.distance/FACE_LIMIT)*100):null):Math.round(x.score*100),sub=x.kind==="face"?(x.known?"Face memory match":"Not in the local index"):"Object detected";return `<div class="result-row"><i class="result-mark ${x.kind}"></i><div class="result-label"><strong>${escape(x.label)}</strong><span>${sub}</span></div><span class="confidence">${conf===null?"—":`${conf}%`}</span></div>`}).join("")}
function draw(results){let sw=active?.videoWidth||active?.naturalWidth||0,sh=active?.videoHeight||active?.naturalHeight||0;if(!sw||!sh)return;let r=el.stage.getBoundingClientRect(),d=devicePixelRatio||1,c=el.overlay.getContext("2d"),s=Math.min(r.width/sw,r.height/sh),ox=(r.width-sw*s)/2,oy=(r.height-sh*s)/2;el.overlay.width=Math.round(r.width*d);el.overlay.height=Math.round(r.height*d);c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);c.textBaseline="middle";for(let x of results){let l=ox+x.box.x*s,t=oy+x.box.y*s,w=x.box.width*s,h=x.box.height*s,color=x.kind==="face"?"#70d1bd":"#e66944",label=x.kind==="face"&&!x.known?"UNKNOWN FACE":x.label.toUpperCase();c.strokeStyle=color;c.lineWidth=2;c.strokeRect(l,t,w,h);c.font="800 10px Arial";let lw=Math.min(c.measureText(label).width+15,Math.max(52,r.width-l)),lt=Math.max(oy,t-20);c.fillStyle=color;c.fillRect(l,lt,lw,18);c.fillStyle="#161817";c.fillText(label,l+7,lt+9)}}
async function scan(){if(!ready||!active||scanning||!(active.videoWidth||active.naturalWidth))return;scanning=true;try{let found=await faceapi.detectAllFaces(active,new faceapi.TinyFaceDetectorOptions({inputSize:kind==="camera"?192:320,scoreThreshold:.42})).withFaceLandmarks().withFaceDescriptors();if(kind==="photo"||performance.now()>=nextObjects){let d=await objectModel.detect(active,5,.56);objects=d.map(x=>({kind:"object",label:x.class,score:x.score,box:{x:x.bbox[0],y:x.bbox[1],width:x.bbox[2],height:x.bbox[3]}}));nextObjects=performance.now()+(kind==="camera"?1800:Number.MAX_SAFE_INTEGER)}let faces=found.map(x=>{let m=faceMatch(Array.from(x.descriptor));return{kind:"face",label:m.name,known:m.known,distance:m.distance,box:x.detection.box}}),results=[...faces,...objects].sort((a,b)=>(b.score||1)-(a.score||1));renderResults(results);draw(results);if(kind==="photo")el.fileStatus.textContent=`SCAN COMPLETE · ${results.length} RESULT${results.length===1?"":"S"} · LOCAL ONLY`}catch(e){console.error(e);el.scanHint.textContent="Recognition paused. Reload this page if the issue continues.";if(kind==="photo")el.fileStatus.textContent="FILE UPLOADED · RECOGNITION PAUSED"}finally{scanning=false}}
function startScan(){clearInterval(scanTimer);objects=[];nextObjects=0;scan();if(kind==="camera")scanTimer=setInterval(scan,600)}function stopScan(){clearInterval(scanTimer);scanTimer=null;scanning=false}
function setSource(src,type,title){stopScan();active=src;kind=type;el.stage.classList.add("active");el.stage.dataset.source=type;el.sourceTitle.textContent=title.toUpperCase();el.stopButton.disabled=false;el.captureButton.disabled=type!=="camera";renderResults([]);if(ready){el.scanHint.textContent=type==="camera"?"Scanning faces often; objects refresh every few seconds.":"Reading this image locally.";startScan()}}
function stopCamera(){if(cameraStream)cameraStream.getTracks().forEach(x=>x.stop());cameraStream=null;el.camera.srcObject=null;el.captureButton.disabled=true}
function reset(){stopScan();stopCamera();if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null;active=null;kind="";el.stage.classList.remove("active");delete el.stage.dataset.source;el.photo.removeAttribute("src");el.sourceTitle.textContent="NO SOURCE";el.stopButton.disabled=true;el.cameraButton.innerHTML="<span>●</span> OPEN CAMERA";el.overlay.getContext("2d").clearRect(0,0,el.overlay.width,el.overlay.height);el.fileStatus.hidden=true;renderResults([]);el.scanHint.textContent=ready?"Open the camera or load an image.":"Models are warming up."}
async function openCamera(){if(!navigator.mediaDevices?.getUserMedia){el.scanHint.textContent="Camera access is not available in this browser. Try LOAD IMAGE.";return}try{stopCamera();cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720},frameRate:{ideal:24,max:30}},audio:false});el.camera.srcObject=cameraStream;await new Promise(ok=>el.camera.onloadedmetadata=ok);await el.camera.play();setSource(el.camera,"camera","live camera");el.cameraButton.innerHTML="<span>●</span> CAMERA OPEN"}catch(e){console.error(e);el.scanHint.textContent="Camera permission was not granted. You can still load an image."}}
async function openPhoto(file){if(!file)return;stopCamera();stopScan();if(photoURL)URL.revokeObjectURL(photoURL);el.fileStatus.hidden=false;el.fileStatus.textContent=`FILE UPLOADED · ${file.name} · ${(file.size/1048576).toFixed(1)} MB · PREPARING FAST SCAN`;try{let image=await toImage(file),edge=Math.max(image.naturalWidth,image.naturalHeight),limit=1600;if(edge>limit){let scale=limit/edge,canvas=document.createElement("canvas");canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext("2d",{alpha:false}).drawImage(image,0,0,canvas.width,canvas.height);let blob=await new Promise(ok=>canvas.toBlob(ok,"image/jpeg",.9));photoURL=URL.createObjectURL(blob)}else photoURL=URL.createObjectURL(file);el.photo.onload=()=>{el.fileStatus.textContent=`FILE UPLOADED · ${file.name} · READING FACE & OBJECTS`;setSource(el.photo,"photo",file.name.length>24?"selected image":file.name)};el.photo.src=photoURL;el.imageInput.value=""}catch(error){console.error(error);el.fileStatus.textContent="FILE COULD NOT BE PREPARED · TRY A DIFFERENT IMAGE"}}
function updateFiles(){let files=[...el.enrollmentImages.files].slice(0,MAX_PHOTOS);el.dropZone.classList.toggle("has-files",!!files.length);el.fileCount.textContent=files.length?`${files.length} photo${files.length===1?"":"s"} ready · only face descriptors will be saved`:"1–6 images · the photos are not kept"}
function setFiles(files){let d=new DataTransfer();files.slice(0,MAX_PHOTOS).forEach(x=>d.items.add(x));el.enrollmentImages.files=d.files;updateFiles()}
function openEnroll(file){if(!ready){el.scanHint.textContent="Face enrollment will be available once the local models have loaded.";return}el.enrollForm.reset();el.enrollFeedback.textContent="";file?setFiles([file]):updateFiles();el.enrollDialog.showModal();setTimeout(()=>el.personName.focus(),100)}
function capture(){if(kind!=="camera"||!el.camera.videoWidth)return;let c=document.createElement("canvas");c.width=el.camera.videoWidth;c.height=el.camera.videoHeight;c.getContext("2d").drawImage(el.camera,0,0,c.width,c.height);c.toBlob(b=>{if(b)openEnroll(new File([b],`northstar-face-${Date.now()}.jpg`,{type:"image/jpeg"}))},"image/jpeg",.93)}
function toImage(file){return new Promise((ok,no)=>{let i=new Image(),u=URL.createObjectURL(file);i.onload=()=>{URL.revokeObjectURL(u);ok(i)};i.onerror=()=>{URL.revokeObjectURL(u);no(new Error("That image could not be read."))};i.src=u})}
async function enroll(event){event.preventDefault();let name=el.personName.value.trim(),files=[...el.enrollmentImages.files].slice(0,MAX_PHOTOS);if(!name||!files.length)return;el.savePersonButton.disabled=true;el.savePersonButton.textContent="READING FACE…";let ds=[];try{for(let n=0;n<files.length;n++){el.enrollFeedback.textContent=`Looking at image ${n+1} of ${files.length}…`;let i=await toImage(files[n]),d=await faceapi.detectSingleFace(i,new faceapi.TinyFaceDetectorOptions({inputSize:416,scoreThreshold:.35})).withFaceLandmarks().withFaceDescriptor();if(d)ds.push(Array.from(d.descriptor))}if(!ds.length)throw new Error("No clear face was found. Use a well-lit, front-facing photo with one person.");let p={id:crypto.randomUUID(),name,descriptors:ds,createdAt:new Date().toISOString()};await put(p);people.push(p);renderPeople();el.enrollDialog.close();setStatus(`LOCAL MODELS READY · ${name.toUpperCase()} SAVED`,true);if(active)scan()}catch(e){el.enrollFeedback.textContent=e.message||"Could not save this face. Try a different photo."}finally{el.savePersonButton.disabled=false;el.savePersonButton.textContent="SAVE FACE MEMORY"}}
function normal(v){let m=v.reduce((a,x)=>a+x,0)/v.length,s=Math.sqrt(v.reduce((a,x)=>a+(x-m)**2,0)/v.length)||1;return v.map(x=>(x-m)/s)}
function average(samples){let n=samples[0]?.length||0;return normal(Array.from({length:n},(_,i)=>samples.reduce((a,x)=>a+x[i],0)/samples.length))}
function voiceFeature(){if(!audioAnalyser||!freq||!time)return null;audioAnalyser.getFloatTimeDomainData(time);if(Math.sqrt(time.reduce((a,x)=>a+x*x,0)/time.length)<.018)return null;audioAnalyser.getByteFrequencyData(freq);let start=3,end=Math.min(150,freq.length),size=Math.max(1,Math.floor((end-start)/20)),out=[];for(let g=0;g<20;g++){let from=start+g*size,to=Math.min(end,from+size),sum=0;for(let i=from;i<to;i++)sum+=freq[i]/255;out.push(sum/Math.max(1,to-from))}return normal(out)}
function voiceMatch(feature){let best={name:"Unknown speaker",distance:Infinity,known:false};for(let p of people)if(Array.isArray(p.voicePrint)&&p.voicePrint.length){let d=distance(feature,p.voicePrint);if(d<best.distance)best={name:p.name,distance:d,known:d<=VOICE_LIMIT}}return best.known?best:{name:"Unknown speaker",distance:best.distance,known:false}}
async function connectMic(){if(!navigator.mediaDevices?.getUserMedia)throw new Error("No microphone access");audioStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false},video:false});let C=window.AudioContext||window.webkitAudioContext;audioContext=new C();await audioContext.resume();audioAnalyser=audioContext.createAnalyser();audioAnalyser.fftSize=2048;audioAnalyser.smoothingTimeConstant=.72;audioContext.createMediaStreamSource(audioStream).connect(audioAnalyser);freq=new Uint8Array(audioAnalyser.frequencyBinCount);time=new Float32Array(audioAnalyser.fftSize)}
async function freeMic(){clearInterval(listenTimer);clearInterval(recordTimer);listenTimer=null;recordTimer=null;if(audioStream)audioStream.getTracks().forEach(x=>x.stop());audioStream=null;if(audioContext)try{await audioContext.close()}catch(e){}audioContext=null;audioAnalyser=null;freq=null;time=null}
async function toggleListen(){if(listening){stopListening();return}if(!voices()){speaker("No voice cues stored","Use TEACH VOICE on a person’s card first.");return}try{await freeMic();await connectMic();listening=true;el.listenButton.textContent="STOP LISTENING";speaker("Listening for a voice…","Speak near the microphone.",true);listenTimer=setInterval(()=>{let f=voiceFeature();if(!f){speaker("Listening for a voice…","No speech detected yet.",true);return}let m=voiceMatch(f);if(m.known)speaker(`${m.name} is likely speaking`,`Voice cue similarity: ${Math.round(Math.max(0,1-m.distance/VOICE_LIMIT)*100)}%`,true);else speaker("Unknown speaker","No close local voice cue found.",true)},360)}catch(e){console.error(e);listening=false;await freeMic();el.listenButton.textContent="START LISTENING";speaker("Microphone is unavailable","Permission was not granted. Voice listening remains off.")}}
function stopListening(message="Microphone is off"){listening=false;freeMic();el.listenButton.textContent="START LISTENING";speaker(message,voices()?"Start listening when you are ready.":"Teach a voice cue, then start listening.")}
function openVoice(id){let p=people.find(x=>x.id===id);if(!p)return;stopListening();voiceId=id;recording=false;voiceSamples=[];el.voicePersonName.textContent=p.name;el.voiceFeedback.textContent="Ready to listen.";el.recordSeconds.textContent="06";el.recordMeter.classList.remove("recording");el.recordVoiceButton.disabled=false;el.recordVoiceButton.textContent="RECORD 6-SECOND SAMPLE";el.voiceDialog.showModal()}
async function recordVoice(){if(recording)return;try{await freeMic();await connectMic();recording=true;voiceSamples=[];let start=performance.now();el.recordMeter.classList.add("recording");el.recordVoiceButton.disabled=true;el.recordVoiceButton.textContent="LISTENING…";el.voiceFeedback.textContent="Speak naturally, at a normal distance from the microphone.";recordTimer=setInterval(()=>{let elapsed=performance.now()-start;el.recordSeconds.textContent=String(Math.max(0,Math.ceil((VOICE_MS-elapsed)/1000))).padStart(2,"0");let f=voiceFeature();if(f)voiceSamples.push(f);if(elapsed>=VOICE_MS)finishVoice()},120)}catch(e){console.error(e);el.voiceFeedback.textContent="Microphone permission was not granted.";recording=false;el.recordVoiceButton.disabled=false;el.recordVoiceButton.textContent="RECORD 6-SECOND SAMPLE"}}
async function finishVoice(){if(!recording)return;recording=false;clearInterval(recordTimer);el.recordMeter.classList.remove("recording");let p=people.find(x=>x.id===voiceId);if(!p||voiceSamples.length<12){await freeMic();el.voiceFeedback.textContent="Too little clear speech was heard. Try again somewhere quieter.";el.recordVoiceButton.disabled=false;el.recordVoiceButton.textContent="RECORD 6-SECOND SAMPLE";return}p.voicePrint=average(voiceSamples);p.voiceUpdatedAt=new Date().toISOString();try{await put(p);renderPeople();el.voiceDialog.close();speaker(`${p.name} has a voice cue`,"Use START LISTENING to identify a likely speaker.")}catch(e){console.error(e);el.voiceFeedback.textContent="The voice cue could not be saved. Please try again.";el.recordVoiceButton.disabled=false;el.recordVoiceButton.textContent="RECORD 6-SECOND SAMPLE"}finally{await freeMic()}}
function closeVoice(){recording=false;freeMic();el.recordMeter.classList.remove("recording");el.voiceDialog.close()}
async function loadModels(){try{setStatus("LOADING LOCAL MODELS…");for(let runtime of [tf,faceapi.tf].filter(Boolean)){try{runtime.enableProdMode?.();await runtime.setBackend("webgl")}catch(error){console.info("Using browser graphics fallback",error)}for(let flag of [["WEBGL_PACK",true],["WEBGL_PACK_DEPTHWISECONV",true],["WEBGL_CPU_FORWARD",false]])try{runtime.env?.().set(...flag)}catch(error){console.info("Optional graphics flag unavailable",flag[0])}}await tf.ready();await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri(FACE_MODEL_URL),faceapi.nets.faceLandmark68Net.loadFromUri(FACE_MODEL_URL),faceapi.nets.faceRecognitionNet.loadFromUri(FACE_MODEL_URL),cocoSsd.load({base:"lite_mobilenet_v2"}).then(m=>objectModel=m)]);ready=true;setStatus("LOCAL MODELS READY · GPU TUNED",true);if(active)startScan()}catch(e){console.error(e);setStatus("MODELS UNAVAILABLE");el.scanHint.textContent="Connect to the internet once to load the public model files, then reload."}}
function events(){el.cameraButton.onclick=openCamera;el.stopButton.onclick=reset;el.captureButton.onclick=capture;el.imageInput.onchange=e=>openPhoto(e.target.files[0]);el.enrollButton.onclick=()=>openEnroll();el.emptyEnrollButton.onclick=()=>openEnroll();el.closeEnrollButton.onclick=()=>el.enrollDialog.close();el.enrollForm.onsubmit=enroll;el.enrollmentImages.onchange=updateFiles;el.clearLogButton.onclick=()=>{renderResults([]);draw([])};el.fullscreenButton.onclick=()=>document.fullscreenElement?document.exitFullscreen():el.stage.requestFullscreen?.();el.privacyButton.onclick=()=>el.privacyDialog.showModal();el.closePrivacyButton.onclick=()=>el.privacyDialog.close();el.listenButton.onclick=toggleListen;el.recordVoiceButton.onclick=recordVoice;el.closeVoiceButton.onclick=closeVoice;el.cancelVoiceButton.onclick=closeVoice;el.voiceDialog.addEventListener("cancel",e=>{e.preventDefault();closeVoice()});addEventListener("resize",()=>draw(lastResults));addEventListener("beforeunload",()=>{stopCamera();freeMic()})}
async function init(){events();try{people=await getPeople();renderPeople()}catch(e){console.error(e);el.scanHint.textContent="The local memory database could not be opened."}loadModels()}init();
